#Expyriment 0.11.dev5 (Python 3.12.7), .xpe-file, coding: UTF-8
#date: Mon May 05 2025 17:43:35
#sha1: 361522
#modules: 
#display: size=(800, 600), window_mode=False, opengl=2
#os: uname_result(system='Linux', node='Geoff3', release='6.11.0-24-generic', version='#24-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 14 18:13:56 UTC 2025', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
477,stderr,received,'Traceback (most recent call last):'
477,stderr,received,'  File "/home/avalazem/Desktop/Work/Single_Word_Processing_Stage/Long_Range_Agreement/Long_Range_Pilot/Code/long_range.py", line 169, in <module>'
477,stderr,received,'    instructions = stimuli.Picture(str(instruction_image_path))'
477,stderr,received,'                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
477,stderr,received,'  File "/home/avalazem/Desktop/Work/Single_Word_Processing_Stage/lib/python3.12/site-packages/expyriment/stimuli/_picture.py", line 43, in __init__'
477,stderr,received,'    raise IOError(u"The picture file \'{0}\' does not exist".format('
477,stderr,received,"OSError: The picture file '/home/avalazem/Desktop/Work/Single_Word_Processing_Stage/Long_Range_Agreement/Long_Range_Pilot/instructions.png' does not exist"
